### PR TITLE
junit 4.13.2

### PR DESCRIPTION
**Pull request by sullis**
### Description

bump junit to 4.13.2

### Tests

n/a

### CODE REVIEW

**Comment by sullis** [comment]
cc: @junkaixue

**Comment by junkaixue** [comment]
Please follow the our PR template to give descriptions and create issues for tracking.

**Comment by junkaixue** [comment]
@sullis

**Comment by junkaixue** [comment]
The test breaks. Need someone to verify whether it is caused by upgrading.

**Comment by junkaixue** [comment]
Close the PR due to no update for a month.

**Pull request closed without merging**
