### PR TITLE
 Remove resource from customized state if all partitions are gone

### LINKED ISSUE #1410: Remove resource from customized state if all partitions are gone
### Describe the bug
Currently if all partitions of a resource in customized state are gone, the znode itself is still there. This is not optimal, we should delete the znode once the map fields are empty.

### To Reproduce
Delete all partitions from a resource, but the resource znode still exists under customized state.

### Expected behavior
Resource znode is gone

### PR DESCRIPTION
**Pull request by zhangmeng916**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:
Fixes #1410 
Any of the following keywords can be used: close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved)

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

Currently if all partitions of a resource in customized state are gone, the znode itself is still there. This is not optimal, we should delete the znode once the map fields are empty. This PR fixed this issue.

### Tests

- [X] The following is the result of the "mvn test" command on the appropriate module:
helix-core

[WARNING] Tests run: 1208, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 3,965.426 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[WARNING] Tests run: 1208, Failures: 0, Errors: 0, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:06 h
[INFO] Finished at: 2020-09-28T12:01:49-07:00
[INFO] ------------------------------------------------------------------------
                                                                                  

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Review by jiajunwang — COMMENTED** [review]
I revisit the groupcommit logic, I believe we shall do it in the following way.
1. Use groupcommit
2. DataUpdater is not usable if we are using updateProperty (then internally commit()), so we shall use znode delta for removing the partition info from the node.
Example,

        // for "OnOfflineToDROPPED" message, we need to remove the resource key record
        // from the current state of the instance because the resource key is dropped.
        // In the state model it will be stayed as "OFFLINE", which is OK.
        ZNRecord rec = new ZNRecord(_currentStateDelta.getId());
        rec.getMapFields().put(partitionKey, null);
        ZNRecordDelta delta = new ZNRecordDelta(rec, MergeOperation.SUBTRACT);

        List<ZNRecordDelta> deltaList = new ArrayList<ZNRecordDelta>();
        deltaList.add(delta);
        _currentStateDelta.setDeltaList(deltaList);

Set this delta to the updateProperty() input, then the groupcommit will subtract the specified partition map item. ANd it will also remove the node if it is empty.

**Comment by zhangmeng916** [comment]
> ZNRecord rec = new ZNRecord(_currentStateDelta.getId());
>  rec.getMapFields().put(partitionKey, null);
>  ZNRecordDelta delta = new ZNRecordDelta(rec, MergeOperation.SUBTRACT);
> 
>  List<ZNRecordDelta> deltaList = new ArrayList<ZNRecordDelta>();
>  deltaList.add(delta);
>  _currentStateDelta.setDeltaList(deltaList);

@jiajunwang Thanks for the suggestion. Yeah, this works. I looked at this part too, but didn't realize that we can move it to customized state provider.

**Review by jiajunwang — APPROVED** [review]
LGTM!

**Comment by zhangmeng916** [comment]
This PR is ready to merge. Approved by @jiajunwang 
Final commit message:
Remove resource from customized state if all partitions are gone.

**Pull request merged**
