### PR TITLE
Refactorings for helix-view-aggregator test

### PR DESCRIPTION
**Pull request by limbooverlambda**
### Issues
Refactoring the testHelixViewAggregator by removing Thread.sleep and  the verifier in TestHelper to specify a poll frequency for verifications.

- [x] My PR addresses the following Helix issues and references them in the PR description:
#2438

### Description
While looking at the failed test run logs it was observed that one of the rebalance operations (the third rebalance call) was not getting invoked. The assertions to verify the MockViewClusterSpectator state failed after the `Thread.sleep() `expired. The likely hypothesis is that the timeout duration of 7 seconds was not sufficient for the ClusterSpectator state to reach steady state. So instead of leveraging `Thread.sleep() `to wait for the cluster to reach steady state in this PR we are using `TestHelper.verify` to check for the desired state.

### Tests

- The following is the result of the "mvn test" command on the appropriate module:

[INFO] -------------------------------------------------------
[INFO] T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
Start zookeeper at localhost:2183 in thread main
Creating resources ...
Rebalancing resources ...
Rebalancing resources ...
Rebalancing resources ...
AfterClass: TestHelixViewAggregator called.
AfterClass: TestSourceClusterDataProvider called.
AfterClass: TestViewClusterRefresher called.
AfterClass: TestViewClusterDataCache called.
Shut down zookeeper at port 2183 in thread main
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 73.581 s - in TestSuite
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0
[INFO]

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Comment by xyuanlu** [comment]
Could you please check if this tests passed in 20 runs in your local repo?

**Comment by xyuanlu** [comment]
> Could you please check if this tests passed in 20 runs in your local repo?

Could you please add the link the CI executions of your personal repo as a reference? Thanks!

**Comment by limbooverlambda** [comment]
> > Could you please check if this tests passed in 20 runs in your local repo?
> 
> Could you please add the link the CI executions of your personal repo as a reference? Thanks!

Sure, here's the link posting the tests: https://github.com/limbooverlambda/helix/pull/3

**Comment by limbooverlambda** [comment]
> Thanks for updating the test runs! Could you please double check this run? It was #7 in the last batch of 20 runs.. Screenshot 2023-05-22 at 10 12 35 AM

Good catch. I have tweaked the timeout a bit more for the affected path and rerun the tests in my branch: https://github.com/limbooverlambda/helix/pull/4

Let me know if this looks good.

**Comment by xyuanlu** [comment]
@limbooverlambda  Thanks for making the change. Please update final commit message.

**Comment by limbooverlambda** [comment]
> @limbooverlambda Thanks for making the change. Please update final commit message.

+1

**Comment by xyuanlu** [comment]
Thanks for follow up with comment. Normally commit message format is 
```
The code has been reviewed and approved by @reviewer_1
Commit message: xxx
```
example: https://github.com/apache/helix/pull/2489

I will use the PR title this time. Please follow open source format for next PR. :D

**Pull request merged**
