### PR TITLE
Optimize imports for the whole project.

### LINKED ISSUE #561: Reformat all imports
We still have imports that are not in order of helix code style. Need to refactor imports for the whole project.

### PR DESCRIPTION
**Pull request by pkuwm**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #561 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

We have new helix style in Intellij. Most of the files are not following the style for imports. So this PR optimizes all imports for all the files in helix project.

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- [x] The following is the result of the "mvn test" command on the appropriate module:

[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestJobQueueCleanUp.testJobQueueAutoCleanUp » ThreadTimeout Method org.testng....
[ERROR]   TestClusterVerifier.testDisablePartitionAndStopInstance:137 expected:<false> but was:<true>
[INFO]
[ERROR] Tests run: 886, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 35.682 s - in org.apache.helix.tools.TestClusterVerifier
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

END testJobQueueAutoCleanUp at Mon Nov 18 12:09:44 PST 2019, took: 3408ms.
Default Suite
Total tests run: 1, Failures: 0, Skips: 0

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

**Comment by pkuwm** [comment]
This PR is ready to be merged, approved by @narendly 
commit:
```
We have new helix style in Intellij. Most of the files are not following the style for imports. So this PR optimizes all imports for all files in helix project.
```

**Comment by narendly** [comment]
@pkuwm Could you please rebase this change so that it could be merged?

**Comment by narendly** [comment]
@pkuwm One last thing: don't forget to run mvn test  and check the box :) Thanks!

**Comment by narendly** [comment]
@pkuwm Did you run the tests that failed individually? Could you please update with the result for those as well?

**Comment by pkuwm** [comment]
> @pkuwm Did you run the tests that failed individually? Could you please update with the result for those as well?

Yes. Added the results. PR is ready to merge.

**Pull request merged**
