### PR TITLE
[Helix-612] Bump up the version of zkClient and zookeeper to avoid NPE

### PR DESCRIPTION
**Pull request by jicongrui**
Know issue in old zkClient
https://github.com/sgroschupf/zkclient/issues/25

### CODE REVIEW

**Comment by kanakb** [comment]
Could you explain why this change is necessary?

**Comment by jicongrui** [comment]
Copied the description in ticket to pull request description.

**Comment by jicongrui** [comment]
Any update for this request?

**Comment by kishoreg** [comment]
LGTM.

**Pull request merged**
