### PR TITLE
Remove all unused imports

### PR DESCRIPTION
**Pull request by leesf**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR title:

(#396)

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

(Write a concise description including what, why, how)

There are many unused imports in project, we should remove it to keep project clean.

### Tests
- [ ] The following tests are written for this issue:

- [x] The following is the result of the "mvn test" command on the appropriate module:

[ERROR] Failures:
[ERROR]   TestWorkflowControllerDataProvider.testResourceConfigRefresh:62 expected:<5> but was:<4>
[ERROR]   TestDrop.testBasic:113->assertEmptyCSandEV:62 expected:<true> but was:<false>
[ERROR]   TestExternalCmd.testExternalCmd:41 ? IO Cannot run program "F:\community\helix...
[ERROR]   TestZkConnectionLost.testLostZkConnection:140 ? Helix Workflow "testLostZkConn...
[ERROR]   TestClusterMaintenanceMode.testMaxPartitionLimit:296 expected:<true> but was:<false>
[ERROR]   TestControllerLeadershipChange.testMissingTopStateDurationMonitoring:119 expected:<true> but was:<false>
[ERROR] org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceNonRack.test(org.apache.helix.integration.rebalancer.CrushRebalancers.TestCrushAutoRebalanceNonRac
k)
[INFO]   Run 1: PASS
[ERROR]   Run 2: TestCrushAutoRebalanceNonRack.test:153 expected:<true> but was:<false>
[INFO]
[ERROR]   TestDelayedAutoRebalance.testMinimalActiveReplicaMaintain:131->ZkTestBase.validateMinActiveAndTopStateReplica:446 Test-DB-0_0 missing MASTER replica expected:<true> but was:<f
alse>
[ERROR]   TestDelayedAutoRebalanceWithDisabledInstance.testPartitionMovementAfterDelayTime:202->ZkTestBase.validateMinActiveAndTopStateReplica:447 Test-DB-0_0 has less active replica 2
then required 3 expected:<true> but was:<false>
[ERROR]   TestDelayedAutoRebalanceWithRackaware.testMinimalActiveReplicaMaintain:88->TestDelayedAutoRebalance.testMinimalActiveReplicaMaintain:131->ZkTestBase.validateMinActiveAndTopSta
teReplica:446 Test-DB-2_1 missing LEADER replica expected:<true> but was:<false>
[ERROR]   TestClusterInMaintenanceModeWhenReachingMaxPartition.testDisableCluster:118 expected:<true> but was:<false>
[ERROR]   TestClusterInMaintenanceModeWhenReachingOfflineInstancesLimit.testWithDisabledInstancesLimit:141 expected:<true> but was:<false>
[ERROR] org.apache.helix.integration.rebalancer.TestMixedModeAutoRebalance.testUserDefinedPreferenceListsInFullAuto(org.apache.helix.integration.rebalancer.TestMixedModeAutoRebalance)
[ERROR]   Run 1: TestMixedModeAutoRebalance.testUserDefinedPreferenceListsInFullAuto:155 expected:<true> but was:<false>
[INFO]   Run 2: PASS
[ERROR]   Run 3: TestMixedModeAutoRebalance.testUserDefinedPreferenceListsInFullAuto:155 expected:<true> but was:<false>
[ERROR]   Run 4: TestMixedModeAutoRebalance.testUserDefinedPreferenceListsInFullAuto:155 expected:<true> but was:<false>
[INFO]   Run 5: PASS
[ERROR]   Run 6: TestMixedModeAutoRebalance.testUserDefinedPreferenceListsInFullAuto:155 expected:<true> but was:<false>
[ERROR]   Run 7: TestMixedModeAutoRebalance.testUserDefinedPreferenceListsInFullAuto:155 expected:<true> but was:<false>
[INFO]   Run 8: PASS
[INFO]
[ERROR]   TestRoutingTableProviderFromCurrentStates.testRoutingTableWithCurrentStates:152->validate:210 expected:<1> but was:<0>
[ERROR]   TestJobTimeout.testTaskRunningIndefinitely:106 expected:<TASK_ABORTED> but was:<null>
[ERROR]   TestQuotaBasedScheduling.testQuotaConfigChange:273 NullPointer
[ERROR]   TestStopWorkflow.testStopTask ? ThreadTimeout Method org.testng.internal.TestN...
[ERROR]   TestTaskRebalancer.testExpiry:88 expected:<false> but was:<true>
[ERROR]   TestTaskRebalancerStopResume.stopDeleteJobAndResumeNamedQueue ? ThreadTimeout ...
[ERROR]   TestTaskRebalancerStopResume.stopDeleteJobAndResumeRecurrentQueue:310 ? Helix ...
[ERROR]   TestTaskRebalancerStopResume.testStopWorkflowInStoppingState:507 ? ThreadTimeout
[ERROR]   TestTaskRetryDelay.testTaskRetryWithoutDelay:80 expected:<true> but was:<false>
[ERROR]   TestWorkflowTermination.testWorkflowJobFail:222 ? Helix Workflow "testWorkflow...
[ERROR]   TestWorkflowTermination.testWorkflowPausedTimeout:169->verifyWorkflowCleanup:256 expected:<true> but was:<false>
[ERROR]   TestWorkflowTermination.testWorkflowRunningTimeout:130->verifyWorkflowCleanup:256 expected:<true> but was:<false>
[ERROR]   TestWorkflowTermination.testWorkflowSucceed:83 ? Helix Workflow "testWorkflowS...
[ERROR]   TestWorkflowTimeout.testWorkflowTimeoutWhenWorkflowCompleted:115 expected:<true> but was:<false>
[ERROR]   TestClusterStatusMonitorLifecycle.testClusterStatusMonitorLifecycle:274 expected:<true> but was:<false>
[ERROR]   TestTaskPerformanceMetrics.testTaskPerformanceMetrics:119 expected:<true> but was:<false>
[ERROR]   TestGetLastScheduledTaskExecInfo.testGetLastScheduledTaskExecInfo:73 expected:<COMPLETED> but was:<INIT>
[ERROR]   TestClusterVerifier.testResourceSubset:192 expected:<false> but was:<true>
[ERROR]   TestZKClientPool.test:49 ? IO Unable to delete file: \tmp\localhost_21891\data...
[INFO]
[ERROR] Tests run: 824, Failures: 32, Errors: 0, Skipped: 14

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [x] In case of new functionality, my PR adds documentation in the following wiki page:

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

**Comment by narendly** [comment]
Thanks for the PR. We try to stick to the guidelines to keep the quality up, so could you please follow https://github.com/apache/helix/wiki/Pull-Request-Guidelines exactly? Thanks :)

**Comment by leesf** [comment]
@narendly Thanks for your reminder, updated the description.

**Comment by narendly** [comment]
@leesf So I see a lot of failed tests, and this is concerning. But since all the changes are just removing redundant imports, I am convinced that it's the issue with your environment (perhaps your machine isn't powerful enough). Our tests spin up a local ZK and many threads are used to simulate Helix components, so we run tests in big machines. Could you tell us what environment you're using?

Just to be sure, I'll maybe take a diff out of this and could try to run the test suite myself at some point (if you don't have access to a beefy machine). Will update this thread.

**Comment by leesf** [comment]
@narendly Thanks for your reply, my environment is windows7, 64bit, 16G, Intel(R) Core(TM) i7-6700 CPU @ 3.4GHz

**Comment by narendly** [comment]
I'm tracking. I'll run the tests when I get a minute and update this PR :)

**Comment by leesf** [comment]
@narendly Sorry to bother you, could I ask what the progress of the PR?

**Comment by narendly** [comment]
@leesf Thanks for the reminder! I'll run it today and update!

**Comment by narendly** [comment]
@leesf 
I checked out your remote branch and ran the test. See the following:

[INFO] Tests run: 838, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3,086.43 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 838, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  51:31 min
[INFO] Finished at: 2019-08-30T16:52:13-07:00
[INFO] ------------------------------------------------------------------------
[hulee@hulee-ld1 helix-core]$ git branch
  master
* remove_import_hotfix
[hulee@hulee-ld1 helix-core]$ 

Looks like it's all clean. Please follow the merge guidelines to if you want to proceed.

**Comment by leesf** [comment]
Thanks for your kindly help.

**Comment by leesf** [comment]
This PR is ready to be merged, approved by @narendly .

**Pull request merged**
