### PR TITLE
[apache/helix] -- Updated Maps.of to Sets.of for Java-8 build complaince

### PR DESCRIPTION
**Pull request by himanshukandwal**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:
Updated codebase to be build with JDK-8.

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:
We will releasing the Open source Helix on Java 11, but we are updating the codebase to be build compatible with Java-8, so that we can internally release it on Java-8.

### Tests

- [x] The following tests are written for this issue:
N/A

- The following is the result of the "mvn test" command on the appropriate module:

```
[INFO] Reactor Summary for Apache Helix 1.3.2-SNAPSHOT:
[INFO] 
[INFO] Apache Helix ....................................... SUCCESS [  0.876 s]
[INFO] Apache Helix :: Metrics Common ..................... SUCCESS [  1.524 s]
[INFO] Apache Helix :: Metadata Store Directory Common .... SUCCESS [  0.647 s]
[INFO] Apache Helix :: ZooKeeper API ...................... SUCCESS [  2.410 s]
[INFO] Apache Helix :: Helix Common ....................... SUCCESS [  0.488 s]
[INFO] Apache Helix :: Core ............................... SUCCESS [  8.677 s]
[INFO] Apache Helix :: Admin Webapp ....................... SUCCESS [  1.093 s]
[INFO] Apache Helix :: Restful Interface .................. SUCCESS [  2.057 s]
[INFO] Apache Helix :: Distributed Lock ................... SUCCESS [  0.378 s]
[INFO] Apache Helix :: HelixAgent ......................... SUCCESS [  0.792 s]
[INFO] Apache Helix :: Front End .......................... SUCCESS [02:16 min]
[INFO] Apache Helix :: Recipes ............................ SUCCESS [  0.017 s]
[INFO] Apache Helix :: Recipes :: Rabbitmq Consumer Group . SUCCESS [  0.547 s]
[INFO] Apache Helix :: Recipes :: Rsync Replicated File Store SUCCESS [  0.512 s]
[INFO] Apache Helix :: Recipes :: distributed lock manager  SUCCESS [  0.391 s]
[INFO] Apache Helix :: Recipes :: distributed task execution SUCCESS [  0.426 s]
[INFO] Apache Helix :: Recipes :: service discovery ....... SUCCESS [  0.393 s]
[INFO] Apache Helix :: View Aggregator .................... SUCCESS [  0.983 s]
[INFO] Apache Helix :: Meta Client ........................ SUCCESS [  0.610 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:39 min
[INFO] Finished at: 2024-02-09T12:51:40-08:00
[INFO] ------------------------------------------------------------------------
```

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Review by desaikomal — APPROVED** [review]

**Comment by himanshukandwal** [comment]
This PR has been approved by @desaikomal 

Final Commit Message: Updated Helix codebase to be build compatible with JDK-8. Open source release will be based on Java 11,

**Comment by junkaixue** [comment]
@himanshukandwal please resolve the conflict?

**Comment by himanshukandwal** [comment]
> @himanshukandwal please resolve the conflict?

Yes updated now. Thanks @junkaixue for review.

**Comment by junkaixue** [comment]
Thanks. Will merge it after the CI run completes.

**Comment by junkaixue** [comment]
@himanshukandwal This was failed: Error:  Test failed: testEvacuationWithOfflineInstancesInCluster(org.apache.helix.integration.rebalancer.TestInstanceOperation)  Time elapsed: 30.25 s  <<< FAILURE!

Could you please make sure the code does not break it? At the same time, I will trigger another run for this

**Comment by himanshukandwal** [comment]
Hey @junkaixue, I verified locally as well and this was a transient issue. The latest build also passed. I think we are good to merge the PR. Thanks!

https://github.com/apache/helix/actions/runs/7896283276/job/21876936680

**Pull request merged**
