### PR TITLE
Change async API

### PR DESCRIPTION
**Pull request by xyuanlu**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:

#2237

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

This refines async API.
1. Allow caller to pass a context to callback.
2. Change callback type of asyncSet

### Tests

- [X] The following tests are written for this issue:
NA
Test will be added when implementation is added.

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Review by junkaixue — COMMENTED** [review]
Code change is fine to me. But why we need to allow user to pass context? If we already give them callback, why they still need the input

**Comment by xyuanlu** [comment]
The context is passed to user callback. If user need an object while executing callback, we need to provide them the option. 
As a reference, ZK async API provides the same signature. Helix pass a retry event handling object in this context for retry when failure.

**Comment by junkaixue** [comment]
Why the context cannot be passed in callback as an argument?

**Comment by xyuanlu** [comment]
Removed context field as our offline discussion. Caller should maintain and manager object they owned if it is needed in callback function. User object should not be passed to client if client does not use this info.

**Comment by xyuanlu** [comment]
This PR is ready for merge. Commit message:
Update async API for metaclient.

**Pull request merged**
