### PR TITLE
Patch Helix participant auto registration to helix-0.9.9 release

### PR DESCRIPTION
**Pull request by zhangmeng916**
### Issues

- [ ] My PR addresses the following Helix issues and references them in the PR description:

(#200 - Link your issue number here: You can write "Fixes #XXX". Please use the proper keyword so that the issue gets closed automatically. See https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
Any of the following keywords can be used: close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved)

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:
Patch Helix cloud support, i.e., participant auto registration feature to helix 0.9.9.

### Tests

- [X] The following is the result of the "mvn test" command on the appropriate module:

helix-rest:
[INFO] Tests run: 96, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 173.702 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 96, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:57 min
[INFO] Finished at: 2020-11-11T17:55:40-08:00

helix-core:
[INFO]
[ERROR] Failures:
[ERROR]   TestAlertingRebalancerFailure.testTagSetIncorrect:174->checkResourceBestPossibleCalFailureState:310 expected:<true> but was:<false>
[ERROR]   TestTaskNumAttempts.testTaskNumAttemptsWithDelay:76 expected:<2> but was:<1>
[ERROR]   TestTaskRebalancer.timeouts » ThreadTimeout Method org.testng.internal.TestNGM...
[ERROR]   TestGetLastScheduledTaskExecInfo.testGetLastScheduledTaskExecInfo:70 expected:<1605150072385> but was:<1605150071277>
[INFO]
[ERROR] Tests run: 905, Failures: 4, Errors: 0, Skipped: 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:09 h
[INFO] Finished at: 2020-11-11T19:04:30-08:00

Local tests are all passed. These tests are fixed in 1.0 and higher.

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Comment by dasahcc** [comment]
@zhangmeng916 It may be some thing missing from 0.9.8 branch clone... You may need to clone the 0.9,x branch and apply changes. Otherwise, it will be squashed as a one commit:

This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Review by jiajunwang — APPROVED** [review]
I think we don't need a review for a backporting change. Please ensure the commits remain the same unless you need to resolve conflict.

**Comment by jiajunwang** [comment]
> @zhangmeng916 It may be some thing missing from 0.9.8 branch clone... You may need to clone the 0.9,x branch and apply changes. Otherwise, it will be squashed as a one commit:
> 
> This branch cannot be rebased due to conflicts
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

Yes, 0.9.x is the one we shall keep adding the hot fixes. Otherwise, you will miss the other fixes.

**Comment by jiajunwang** [comment]
As requested by Meng, I have reset the helix-0.9.x branch. She will regenerate a new patch.

**Pull request merged**
