### PR TITLE
Use ZooKeeper 3.5.9 in zookeeper-api instead

### LINKED ISSUE #1973: [Failed CI Test] beforeSuite(org.apache.helix.zookeeper.routing.TestHttpZkFallbackRoutingDataReader)
This issue is created for tracking unstable test: beforeSuite(org.apache.helix.zookeeper.routing.TestHttpZkFallbackRoutingDataReader)

### PR DESCRIPTION
**Pull request by narendly**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1973

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

With the upgrade of apache zookeeper version, snappy-java was missing in the dependency. This commit adds snappy-java and removes unused imports in osgi declaration. Also, using ZooKeeper 3.5.9 in zookeeper-api instead because 3.6.0+ causes some tests to fail in zookeeper-api.

### Tests

- [ ] The following tests are written for this issue:

N/A

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Review by qqu0127 — APPROVED** [review]
Thanks for the quick fix, LGTM.

**Comment by desaikomal** [comment]
LGTM.. thanks for fixing it quickly..

**Review by rahulrane50 — APPROVED** [review]
LGTM! Thanks for the fix!

**Comment by narendly** [comment]
This PR is ready to be merged, approved by @qqu0127 @desaikomal @rahulrane50 . The CI workflow was successful: https://github.com/apache/helix/runs/5522370317?check_suite_focus=true

**Pull request merged**
