### PR TITLE
upgrade helix-front from Angular 5.1 to 5.2

### PR DESCRIPTION
**Pull request by micahstubbs**
### Issues

#2053: Increment progress towards the goal of upgrading helix-front to the current version of Angular.

### Description

This PR upgrade helix-front from Angular 5.1 to 5.2.

### Tests

Let's test the upgrade from Angular 5.1 to Angular 5.2:

- [x] `npm install` works
- [x] `npm run build` works
- [x] `npm start` works
- [x] `npm run test` runs and passes
- [x] `npm run lint` runs and passes

Helix UI renders with 0 errors and 1 warning in the browser console. The warning is understandable since I did not specify the optional config necessary for the Piwik analytics library to work.
Screen Shot 2022-05-02 at 3 58 18 PM

`npm run test` results

Screen Shot 2022-05-02 at 4 00 50 PM

### CODE REVIEW

**Comment by micahstubbs** [comment]
Notes ported over from #2053 comments: 

Let's upgrade a minor version from Angular 5.1 to Angular 5.2

We will use https://update.angular.io/?l=3&v=5.1-5.2 as our guide.

Screen Shot 2022-05-02 at 3 39 29 PM

**Comment by micahstubbs** [comment]
The **Before Updating** checklist is complete. Most of these didn't apply. You can see in the [5.1-->5.2 PR diff](https://github.com/apache/helix/pull/2078/files) which changes were relevant to our helix-front codebase.

Screen Shot 2022-05-02 at 3 41 48 PM

**Comment by junkaixue** [comment]
Thanks @micahstubbs. But this make me a little bit confusing. You have two PRs to upgrade Angular, one is this 5.1 to 5.2 and another is to 13.

**Comment by micahstubbs** [comment]
Hi @junkaixue, I understand how this could be confusing.

The Angular 13 PR was an initial attempt to do a "one-shot" upgrade and then fix any issues afterwards.

That approach is currently stuck on a difficult to debug issue, so after talking with other reviewers, we decided to break the "one-shot" PR into smaller PRs, one for each version increment.

I'll go ahead and close the Angular 13 PR, to make it more clear what our current upgrade strategy is.

Thanks for asking.

**Comment by micahstubbs** [comment]
CI fails due to a flaky helix-rest test, best I can tell. This failure appears unrelated to the helix-front UI changes in this PR.

https://github.com/apache/helix/runs/6265663671?check_suite_focus=true

Screen Shot 2022-05-08 at 9 44 35 AM

**Comment by micahstubbs** [comment]
see also this CI failure on another **helix-front** PR:  https://github.com/apache/helix/pull/2074#issuecomment-1122688228

**Comment by micahstubbs** [comment]
This PR is ready to be merged. 

## final commit message

`upgrade helix-front to Angular 5.2`

**Comment by micahstubbs** [comment]
This PR is ready to be merged.

Conflicts have been resolved.

final commit message

upgrade helix-front to Angular 5.2

**Comment by junkaixue** [comment]
This is not the right way to solve diff between master branch and local branch. You should use rebase instead of merge.

**Comment by micahstubbs** [comment]
Thanks for the feedback @junkaixue. Would you like me to create a new PR for this diff?

**Comment by junkaixue** [comment]
Let's do that. The more I care is about the commits in the middle should not be involved in your PR.

**Comment by micahstubbs** [comment]
closed in favor of https://github.com/apache/helix/pull/2108

**Pull request closed without merging**
