### PR TITLE
fixed bug #1517: Controller tutorial doc page compilation errors

### LINKED ISSUE #1517: Controller tutorial doc page leads to compilation errors
Source code provided on the following pages:
https://helix.apache.org/0.9.8-docs/tutorial_controller.html
https://helix.apache.org/1.0.1-docs/tutorial_controller.html
Has compilation errors on those lines:
```java
manager.addConfigChangeListener(controller);  // compilation error
manager.addLiveInstanceChangeListener(controller);
manager.addIdealStateChangeListener(controller);
manager.addExternalViewChangeListener(controller);  // compilation error
manager.addControllerListener(controller);
```

### PR DESCRIPTION
**Pull request by bfreuden**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Resolves #1517 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

I fixed them by doing the same thing as the ``addListenersToController`` method of ``org.apache.helix.manager.zk.ControllerManagerHelper``.
As the code is different between 0.9.8 and 1.0.1, the documentation fix also differs accordingly (0.9.8 and 1.0.1 docs).

### CODE REVIEW

**Review by narendly — APPROVED** [review]
Thank you. Controller should listen on InstanceConfig and ResourceConfig, and I'm not sure why the old tutorial didn't contain that. This is helpful and thanks for the contribution!

**Comment by narendly** [comment]
@bfreuden you could follow the rest of the steps described here: https://github.com/apache/helix/wiki/Pull-Request-Merge-Steps. Then we can merge this change into master. Thanks again!

**Comment by bfreuden** [comment]
@narendly thank you for your positive feedback. I'm glad this little contribution is helpful.

**Comment by bfreuden** [comment]
This PR is ready to be merged.

**Pull request merged**
