### PR TITLE
Change instance status in Helix UI to be colorblind-friendly

### LINKED ISSUE #1758: Instance online/offline status colors in Helix UI aren't colorblind-friendly
**Is your feature request related to a problem? Please describe.**
The green and red colors used to indicate online/offline status are indistinguishable with certain colorblindness conditions.

**Describe the solution you'd like**
Change the colors for online/offline status.

### PR DESCRIPTION
**Pull request by rabashizade**
This commit changes the green/red instance status colors in Helix UI to blue/black to be more colorblind-friendly.

### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1758 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR changes the instance online/offline status colors in Helix UI from green/red to blue(#2196F3)/black(#212121) to be colorblind-friendly. The colors are chosen such that they have a contrast ratio of at least 3:1 against each other and the background. Moreover, a checkmark is placed in the icon for online status, and a cross (x) for the offline. Screenshots of the changes are the following:

Screen Shot 2021-05-26 at 1 16 09 PM Screen Shot 2021-05-26 at 1 16 22 PM

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Comment by jiajunwang** [comment]
@rabashizade Thanks for the PR. I just want to understand if this is the standard way to help colorblind-friendly? Do you have any official reference, like industrial standard, that indicates this would help everyone?
IMHO, adding some letters, or make the picture contains a pattern (like 🚫) would be more helpful. But I'm not sure if these are standard ways or not.

**Comment by rabashizade** [comment]
> @rabashizade Thanks for the PR. I just want to understand if this is the standard way to help colorblind-friendly? Do you have any official reference, like industrial standard, that indicates this would help everyone?
> IMHO, adding some letters, or make the picture contains a pattern (like 🚫) would be more helpful. But I'm not sure if these are standard ways or not.

Thanks for the feedback. I updated the PR description based on some industry standards and added screenshots of the changes. I also improved the colors used and added signs for the statues (checkmark for online and X for offline).

**Review by jiajunwang — APPROVED** [review]
LGTM!

**Comment by jiajunwang** [comment]
I guess there would be more changes like this needed in the other pages of helix-ui. But let's start from here.

**Comment by rabashizade** [comment]
This PR is ready to be merged, approved by @jiajunwang.

**Commit message:**

Change instance status in Helix UI to be colorblind-friendly

This commit changes the instance online/offline status colors in Helix UI from green/red to blue(#2196F3)/black(#212121) to be more colorblind-friendly. The colors are chosen such that they have a contrast ratio of at least 3:1 against each other and the background. Moreover, a checkmark is placed in the icon for online status, and a cross (x) for the offline.

**Pull request merged**
