### PR TITLE
Add TTL and Container Modes to ZkClient and BaseDataAccessor APIs

### LINKED ISSUE #2081: API methods in zookeeper-api don't support extended types
**Is your feature request related to a problem? Please describe.**
Zookeeper versions 3.5.3+ support some extended types for creating ZNodes, namely CONTAINER, PERSISTENT_WITH_TTL, and PERSISTENT_SEQUENTIAL_WITH_TTL. However, API methods that can support these types haven't been added to zookeeper-api module.

**Describe the solution you'd like**
Add API methods for Zookeeper extended types to zookeeper-api.

### PR DESCRIPTION
**Pull request by rabashizade**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #2081 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR adds methods that support creating container nodes and persistent nodes with TTL to several classes, including ZkConnection, ZkClient and its descendants in zookeeper-api, and BaseDataAccessors in helix-core.

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Review by qqu0127 — APPROVED** [review]
This is just rebase to master branch? 
LGTM assuming all commits have been reviewed separately.

**Comment by rabashizade** [comment]
> This is just rebase to master branch? LGTM assuming all commits have been reviewed separately.

Thank you for the review. Yes, each commit has been separately reviewed in a PR for the feature branch.

**Review by desaikomal — APPROVED** [review]
thanks for confirming it. LGTM as well.

**Comment by rabashizade** [comment]
This PR is ready to be merged, approved by @qqu0127 and @desaikomal.

**Pull request merged**
