### PR TITLE
Update some website links to https

### LINKED ISSUE #2310: some links on the website are http where they could be https
I intend to provide a PR updating some of those

### PR DESCRIPTION
**Pull request by raboof**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #2310

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

Update some website links to https

### Tests

- [x] The following tests are written for this issue:

None

- [x] The following is the result of the "mvn test" command on the appropriate module:

Not running due to zookeeper connection errors

### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation (Optional)

- [x] In case of new functionality, my PR adds documentation in the following wiki page:

n/a

### Code Quality

- [x] My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

n/a

### CODE REVIEW

**Comment by junkaixue** [comment]
Hi @raboof, thanks for contributing Helix! This PR is excellent. But please follow the template guidance: https://github.com/apache/helix/wiki/Pull-Request-Description-Template

And also follow the steps of PR merge: https://github.com/apache/helix/wiki/Pull-Request-Merge-Steps

**Comment by raboof** [comment]
Updated PR body

**Review by junkaixue — APPROVED** [review]
Thanks for the contribution. LGTM

**Comment by raboof** [comment]
This PR is ready to be merged

**Pull request merged**
