### PR TITLE
Add hashCode() to AssignableReplica and fix logic in hash-based collection

### PR DESCRIPTION
**Pull request by qqu0127**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:
Fixes https://github.com/apache/helix/issues/2299 

### Description

- [X] Here are some details about my PR, including screenshots of any UI changes:

Without the fix, the class `AssignableReplica` is breaking the contract in `Object.hashCode()`. If only override `equals()`, a hashset may contain two equaled objects. See also https://stackoverflow.com/questions/2265503/why-do-i-need-to-override-the-equals-and-hashcode-methods-in-java.

Overriding hashCode() in `AssignableReplica` to make it consistent with `equals()`.
Also changing the appearance of `Set<AssignableReplica>` to `List`, which is the way it should be. In most use cases there is a collection of replicas with same (resource, partition, state), using hashset is confusing to start with.

This class is fundamental to WAGED rebalancer. Using list also has performance improvement over set.

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- The following is the result of the "mvn test" command on the appropriate module:

[INFO] Tests run: 1326, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6,965.344 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1326, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:report (generate-code-coverage-report) @ helix-core ---
[INFO] Loading execution data file /Users/qqu/workspace/qqu-helix/helix-core/target/jacoco.exec
[INFO] Analyzed bundle 'Apache Helix :: Core' with 797 classes
[INFO] 
[INFO] --- maven-bundle-plugin:5.1.4:bundle (default-bundle) @ helix-core ---

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Comment by junkaixue** [comment]
Could you please elaborate why the Set does not work? We are using set because of we do observe the list operation can cause a huge delay in computation for other scenarios.

Unless we have a strong reason using List or clear drawback for Set, I prefer to keep the set.

**Comment by jiajunwang** [comment]
I had tried this when WAGED is firstly developed. What I can tell is that performance will be terrible and the rebalancer basically unusable in middle to large size clusters.

And to be complete, I also tried to add a hashcode then using a map with item counts as value. I remember the speed is better, but not good enough for production usage.

Do we have any logic fails that makes you believe we should add hashcode back? I mean what's the real problem?

**Comment by jiajunwang** [comment]
Actually, if you really want to make things straight, I would suggest changing the equal method, so different objects won't be equal and we can add another method just to compare replica's ID. But I forgot if any library code calls equal inside so we won't be able to promote the new equal method... Just my two cents.

Overall performance is one of the most important things for the rebalancer and we cannot compromise.

**Comment by qqu0127** [comment]
> Could you please elaborate why the Set does not work? We are using set because of we do observe the list operation can cause a huge delay in computation for other scenarios.
> 
> Unless we have a strong reason using List or clear drawback for Set, I prefer to keep the set.

Please refer to https://stackoverflow.com/questions/2265503/why-do-i-need-to-override-the-equals-and-hashcode-methods-in-java, we are not using it right. Two "equaled" object will be hashed into different bucket (or with collision, same bucket). There is no point using set over list in our case if `hashCode` isn't overriden.

**Comment by qqu0127** [comment]
> I had tried this when WAGED is firstly developed. What I can tell is that performance will be terrible and the rebalancer basically unusable in middle to large size clusters.
> 
> And to be complete, I also tried to add a hashcode then using a map with item counts as value. I remember the speed is better, but not good enough for production usage.
> 
> Do we have any logic fails that makes you believe we should add hashcode back? I mean what's the real problem?

I don't quite understand the performance part. First, we are not using contains logic, so basically it's plain container or collection for either list or set. Second, a simple benchmarking test shows list has better performance in both time and memory, similar as in https://stackoverflow.com/questions/10799417/performance-and-memory-allocation-comparison-between-list-and-set

The most fundamental problem is this class is violating the contract of Object.hashCode, it confuses people as two equaled objects can have different hashcode, what's worse, as in the description, it doesn't work well with hash-based collections. There is no direct logic breaking. This is a cleanup and performance boost.

**Comment by desaikomal** [comment]
@jiajunwang - can you please elaborate on performance concern? From correctness point of view, @qqu0127 seems to be correct? we will have same kind of objects hashed differently.  We have 2 things here:
(a) Adding 'hashCode' 
(b) choosing List over Set.

I think (a) is required for correctness. (b) is for performance based on what Quincy has pointed out. Are we in disagreement on (a) or (b) ?

**Comment by jiajunwang** [comment]
I had to download the code to remind myself what happened exactly...
Since we have added an index to cover searching functionality, I agree that it seems the Set here can be changed to List. I guess it was carried over from the performance enhancement attempts I tried as I mentioned earlier in this thread.

Given that saying, I think we should consider removing the equals() override instead of adding new hashcode override. At a high level, AssignableReplica objects are different event their resource/partition/state keys are the same. So I'm actually more concerned of adding hashCode which makes 2 different replica object identical.
I tried to search for all AssignableReplica usages to confirm that if equals is still needed. Seems OK to remove, but please double check : )
Also, please run some benchmark to ensure that we don't miss anything.

And this is a good catch. Thanks for the change!

**Comment by qqu0127** [comment]
@jiajunwang 
> So I'm actually more concerned of adding hashCode which makes 2 different replica object identical.

Adding hashCode won't make them identical, (well, in fact it's happening because `equals()`), having same hashCode doesn't necessarily mean the two objects are same, but two equaled objects must have same hash. Adding hashCode isn't making it worse or better, but make it consistent.

Also FYI, `equals()` is used in https://github.com/apache/helix/blob/master/helix-core/src/main/java/org/apache/helix/controller/rebalancer/waged/model/AssignableNode.java#L149
So, I'd prefer keeping `equals()` and adding `hashCode()`

**Comment by junkaixue** [comment]
> I had to download the code to remind myself what happened exactly... Since we have added an index to cover searching functionality, I agree that it seems the Set here can be changed to List. I guess it was carried over from the performance enhancement attempts I tried as I mentioned earlier in this thread.
> 
> Given that saying, I think we should consider removing the equals() override instead of adding new hashcode override. At a high level, AssignableReplica objects are different event their resource/partition/state keys are the same. So I'm actually more concerned of adding hashCode which makes 2 different replica object identical. I tried to search for all AssignableReplica usages to confirm that if equals is still needed. Seems OK to remove, but please double check : ) Also, please run some benchmark to ensure that we don't miss anything.
> 
> And this is a good catch. Thanks for the change!

I remember the old set better than list is when we have removeAll operation :). If we have this kind of operation, the performance will be huge slow.

**Review by desaikomal — APPROVED** [review]
I agree with correctness part, and based on link, i agree performance wise too. 
Now about specific perf in our code base, we can try it if required with simulation.

**Comment by rahulrane50** [comment]
@qqu0127 just 2 cents about performance, the performance hit you will see only for huge lists (as mentioned by jiajun for large clusters). In the stackoverflow link you added in prev comment see 5th answer it talks about that. Unless it's really required or have any benefits to back with benchmarking results, it could be risky to do it.

**Comment by desaikomal** [comment]
@jiajunwang - sorry to bug you but can you please let us know if this change is OK? 
Please help us review this and WAGED change. Please.

**Comment by desaikomal** [comment]
@qqu0127 - are you still planning to checkin this fix?

thanks,
komal

**Comment by junkaixue** [comment]
Close it. Free feel to reopen another PR

**Pull request closed without merging**
