### PR TITLE
update parent and site plugin

### PR DESCRIPTION
**Pull request by hboutemy**
### Issues

- [ ] My PR addresses the following Helix issues and references them in the PR description:

(#200 - Link your issue number here: You can write "Fixes #XXX". Please use the proper keyword so that the issue gets closed automatically. See https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
Any of the following keywords can be used: close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved)

### Description

- [ ] Here are some details about my PR, including screenshots of any UI changes:

(Write a concise description including what, why, how)

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Comment by junkaixue** [comment]
Thanks @hboutemy and @olamy for helping us on this! I had a huge headache on the web publishing. I think I need to bump the maven site plugin version in website/pom.xml as well, right?

I tried the latest commit. It will give me same error if I tried to bump maven site plugin  in website/pom.xml and failed to build.

SiteToolException: Error parsing site descriptor: TEXT must be immediately followed by END_TAG and not START_TAG (position: START_TAG seen ...<head>\n      <script type="text/javascript">... @41:38) -> [Help 1]

@hboutemy could you please give us any pointers that what we can do with site.xml? Or anything I shall do for this repo? Thank you very much again for the help!

**Comment by olamy** [comment]
@junkaixue I cannot reproduce the error. can you copyp/paste the exact log? (I guess it's related to your environment).
I will try to deploy a new version of the website. Could we remove some old version to make the deployment faster?

**Comment by hboutemy** [comment]
@junkaixue see #1910

**Comment by junkaixue** [comment]
Thanks @olamy. I already removed 0.6, 0.7 versions. Will try to remove some other old versions.

**Pull request merged**
