### PR TITLE
jackson-databind 2.12.7.1

### LINKED ISSUE #2764: upgrade jackson-databind to 2.12.7.1
jackson-databind 2.12.6.1 has 2 CVEs

https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.12.6.1

jackson 2.12.7.1 works best with jackson-core 2.12.7

A number of dependabot PRs were created but closed without being merged - eg https://github.com/apache/helix/pull/2284

### PR DESCRIPTION
**Pull request by pjfanning**
### Issues

- [X] My PR addresses the following Helix issues and references them in the PR description:

resolves #2764 

### Description

jackson-databind 2.12.6.1 is insecure - see https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind

### Test

[ERROR] Failures: 
[ERROR]   TestInstanceOperation.testEvacuationWithOfflineInstancesInCluster:1357->verifier:1415 expected:<true> but was:<false>
[INFO] 
[ERROR] Tests run: 1414, Failures: 1, Errors: 0, Skipped: 6
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:12 h
[INFO] Finished at: 2024-02-29T16:23:33-08:00
[INFO] ------------------------------------------------------------------------

[INFO] Tests run: 28, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:report (generate-code-coverage-report) @ helix-core ---
[INFO] Loading execution data file /Users/jxue/tools/helix/helix-core/target/jacoco.exec
[INFO] Analyzed bundle 'Apache Helix :: Core' with 950 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:10 min
[INFO] Finished at: 2024-03-01T14:05:54-08:00
[INFO] ------------------------------------------------------------------------

### CODE REVIEW

**Comment by junkaixue** [comment]
Please use the template and run all the tests...

**Comment by pjfanning** [comment]
@junkaixue which extra tests do I need to run that are not being run by GitHub CI right now?

**Comment by junkaixue** [comment]
At least the helix-core. CI is using the Linux box running on remote. We also need a local laptop tests run to make sure the laptop has the same compatibility.

**Comment by junkaixue** [comment]
Updated the running result locally.

**Pull request merged**
