### PR TITLE
Compilation and execution errors in tutorial doc page

### LINKED ISSUE #1516: Tutorial doc page leads to compilation and execution errors
Source code provided on the following pages:
https://helix.apache.org/0.9.8-docs/Tutorial.html
https://helix.apache.org/1.0.1-docs/Tutorial.html
Has the following problems:
- does not compile because of ports arrays not being a String array
- fails to run because the DROPPED state is not declared
- is a bit confusing for beginners because of MASTER, SLAVE and OFFLINE variables that look like predefined variables having a special meaning to Helix but (as far as I understand) they are just opaque String to Helix. So I propose to replace them with actual strings.

I will issue a pull request shortly.

### PR DESCRIPTION
**Pull request by bfreuden**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Resolves #1516 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

I fixed some compilation and executions errors in code samples delivered in the tutorial documentation. 
I also added the following comment (about creating a state model) since I think it might help beginners like me.
But it should be reviewed by an Helix expert (and English native speaker):
```java
// Define your own states: those are opaque strings to Helix
// Only the topology of the state machine (initial state, transitions, priorities, final DROPPED state) is meaningful to Helix
```

### CODE REVIEW

**Review by narendly — APPROVED** [review]

**Comment by narendly** [comment]
@bfreuden thanks. could you please rename the PR title so that it's descriptive?

**Comment by bfreuden** [comment]
@narendly You're right! I've renamed the PR.

**Comment by bfreuden** [comment]
@narendly I'm afraid I'm not sure I understand this (from https://github.com/apache/helix/wiki/Pull-Request-Merge-Steps):
 _If this is the case, you must include one final commit message for the squashed commit in your final comment._

Should I simply leave a final comment like this?
> This ** is ready to be merged.
> fixed bug #1516: Tutorial doc page leads to compilation and execution errors

**Comment by jiajunwang** [comment]
@bfreuden Thanks for the PR. Usually, we do squash and merge. So it would be helpful if you write down the final comment for the merged commit. So that we don't put anything wrong.

**Comment by bfreuden** [comment]
@jiajunwang Thank you too for taking care of it. 
I'm truly sorry but I don't understand the procedure regarding the final commit message for squashed commits (from https://github.com/apache/helix/wiki/Pull-Request-Merge-Steps).
So just to be sure for next time (and sorry for asking the question twice): should I've simply had left a final PR comment like this?

> This PR is ready to be merged.
fixed bug #1516: Tutorial doc page leads to compilation and execution errors

**Pull request merged**
