### PR TITLE
[doc] Update README.md for format issues

### PR DESCRIPTION
**Pull request by Sunt-ing**
Description
I have read the PR template and found that this PR was so trivial that it should be reviewed directly.

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by junkaixue** [comment]
Thanks contributing Helix. For the description section, if you dont have a clear issue to link, please remove the checks. For other sections, if they are not applied, please leave it unselected but do not remove them.

**Comment by Sunt-ing** [comment]
@jiajunwang Hello, could you please review this PR? I think it should be very easy for you to review. Thanks!

**Comment by jiajunwang** [comment]
> @jiajunwang Hello, could you please review this PR? I think it should be very easy for you to review. Thanks!

Since @junkaixue is already reviewing the PR, could you please respond to his comment : )

**Comment by junkaixue** [comment]
Please update PR correspondingly. Otherwise, we may close it.

**Pull request closed without merging**
