### PR TITLE
setup cluster for ServiceDiscoveryDemo

### LINKED ISSUE #2811: service-discovery-demo.sh run fail
### Describe the bug

branch: master

run command  
./service-discovery-demo.sh

```
sh service-discovery-demo.sh
START:Service discovery demo mode:WATCH
558  [main] ERROR org.apache.helix.manager.zk.ZKHelixManager [] - fail to createClient. retry 1
org.apache.helix.HelixException: Cluster structure is not set up for cluster: service-discovery-demo
        at org.apache.helix.manager.zk.ZKHelixManager.handleNewSession(ZKHelixManager.java:1384) ~[helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.manager.zk.ZKHelixManager.createClient(ZKHelixManager.java:783) [helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.manager.zk.ZKHelixManager.connect(ZKHelixManager.java:818) [helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.servicediscovery.ServiceDiscovery.start(ServiceDiscovery.java:78) [service-discovery-1.3.2-SNAPSHOT.jar:?]
        at org.apache.helix.servicediscovery.ServiceDiscoveryDemo.demo(ServiceDiscoveryDemo.java:50) [service-discovery-1.3.2-SNAPSHOT.jar:?]
        at org.apache.helix.servicediscovery.ServiceDiscoveryDemo.main(ServiceDiscoveryDemo.java:38) [service-discovery-1.3.2-SNAPSHOT.jar:?]
567  [main] ERROR org.apache.helix.manager.zk.ZKHelixManager [] - fail to createClient. retry 2
org.apache.helix.HelixException: Cluster structure is not set up for cluster: service-discovery-demo
        at org.apache.helix.manager.zk.ZKHelixManager.handleNewSession(ZKHelixManager.java:1384) ~[helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.manager.zk.ZKHelixManager.createClient(ZKHelixManager.java:783) [helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.manager.zk.ZKHelixManager.connect(ZKHelixManager.java:818) [helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.servicediscovery.ServiceDiscovery.start(ServiceDiscovery.java:78) [service-discovery-1.3.2-SNAPSHOT.jar:?]
        at org.apache.helix.servicediscovery.ServiceDiscoveryDemo.demo(ServiceDiscoveryDemo.java:50) [service-discovery-1.3.2-SNAPSHOT.jar:?]
        at org.apache.helix.servicediscovery.ServiceDiscoveryDemo.main(ServiceDiscoveryDemo.java:38) [service-discovery-1.3.2-SNAPSHOT.jar:?]
570  [main] ERROR org.apache.helix.manager.zk.ZKHelixManager [] - fail to createClient. retry 3
org.apache.helix.HelixException: Cluster structure is not set up for cluster: service-discovery-demo
        at org.apache.helix.manager.zk.ZKHelixManager.handleNewSession(ZKHelixManager.java:1384) ~[helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.manager.zk.ZKHelixManager.createClient(ZKHelixManager.java:783) [helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.manager.zk.ZKHelixManager.connect(ZKHelixManager.java:818) [helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.servicediscovery.ServiceDiscovery.start(ServiceDiscovery.java:78) [service-discovery-1.3.2-SNAPSHOT.jar:?]
        at org.apache.helix.servicediscovery.ServiceDiscoveryDemo.demo(ServiceDiscoveryDemo.java:50) [service-discovery-1.3.2-SNAPSHOT.jar:?]
        at org.apache.helix.servicediscovery.ServiceDiscoveryDemo.main(ServiceDiscoveryDemo.java:38) [service-discovery-1.3.2-SNAPSHOT.jar:?]
570  [main] ERROR org.apache.helix.manager.zk.ZKHelixManager [] - fail to connect service-discovery
org.apache.helix.HelixException: Cluster structure is not set up for cluster: service-discovery-demo
        at org.apache.helix.manager.zk.ZKHelixManager.handleNewSession(ZKHelixManager.java:1384) ~[helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.manager.zk.ZKHelixManager.createClient(ZKHelixManager.java:783) ~[helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.manager.zk.ZKHelixManager.connect(ZKHelixManager.java:818) [helix-core-1.3.2-SNAPSHOT.jar:1.3.2-SNAPSHOT]
        at org.apache.helix.servicediscovery.ServiceDiscovery.start(ServiceDiscovery.java:78) [service-discovery-1.3.2-SNAPSHOT.jar:?]
        at org.apache.helix.servicediscovery.ServiceDiscoveryDemo.demo(ServiceDiscoveryDemo.java:50) [service-discovery-1.3.2-SNAPSHOT.jar:?]
        at org.apache.helix.servicediscovery.ServiceDiscoveryDemo.main(ServiceDiscoveryDemo.java:38) [service-discovery-1.3.2-SNAPSHOT.jar:?]
Exception in thread "main" org.apache.helix.HelixException: Cluster structure is not set up for cluster: service-discovery-demo
        at org.apache.helix.manager.zk.ZKHelixManager.handleNewSession(ZKHelixManager.java:1384)
        at org.apache.helix.manager.zk.ZKHelixManager.createClient(ZKHelixManager.java:783)
        at org.apache.helix.manager.zk.ZKHelixManager.connect(ZKHelixManager.java:818)
        at org.apache.helix.servicediscovery.ServiceDiscovery.start(ServiceDiscovery.java:78)
        at org.apache.helix.servicediscovery.ServiceDiscoveryDemo.demo(ServiceDiscoveryDemo.java:50)
        at org.apache.helix.servicediscovery.ServiceDiscoveryDemo.main(ServiceDiscoveryDemo.java:38)
```

### To Reproduce
Steps to reproduce the behavior.
1. checkout master branch 
2. maven build 
3. run ./service-discovery-demo.sh

### Expected behavior

service-discovery-demo.sh run normally

### Additional context
none

### PR DESCRIPTION
**Pull request by JoeCqupt**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #2811 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

setup cluster for ServiceDiscoveryDemo

### Tests

- [x] The following tests are written for this issue:

none

- The following is the result of the "mvn test" command on the appropriate module:

(If CI test fails due to known issue, please specify the issue and test PR locally. Then copy & paste the result of "mvn test" to here.)

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Review by junkaixue — COMMENTED** [review]
Thanks for adding this! Please make sure admin.close() has been called after end of the block.

**Review by junkaixue — APPROVED** [review]

**Comment by junkaixue** [comment]
@JoeCqupt Make sure you have the final message as the merge guidance wiki showed.

**Comment by JoeCqupt** [comment]
I tried to trigger CI to run again by updating the commit, but it was not successful.

The failure of CI build seems to be an accidental event, please trigger CI again.

**Comment by junkaixue** [comment]
@JoeCqupt Please confirm this is the version you would like to check in and leave your final commit message. I think the failure is not related to your change.

**Comment by JoeCqupt** [comment]
> @JoeCqupt Please confirm this is the version you would like to check in and leave your final commit message. I think the failure is not related to your change.

 i confirm

**Pull request merged**
