### PR TITLE
Add 3 Zookeeper CreateMode types to AccessOption

### LINKED ISSUE #1974: Missing Zookeeper CreateModes in AccessOption class
**Is your feature request related to a problem? Please describe.**
There are some CreateModes present in Zookeeper that are not supported in AccessOption class, such as CONTAINER, PERSISTENT_WITH_TTL, etc. These modes can be useful for some applications.

**Describe the solution you'd like**
Add the missing CreateMode types to AccessOption.

### PR DESCRIPTION
**Pull request by rabashizade**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #1974 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

This PR adds the 3 missing CreateMode types to AccessOption class in helix-core: `CONTAINER`, `PERSISTENT_WITH_TTL`, and `PERSISTENT_SEQUENTIAL_WITH_TTL`. These types can be useful for some applications that require TTL support or implement locking, etc.

### Tests

- [x] The following tests are written for this issue:

None

- The following is the result of the "mvn test" command on the appropriate module:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Helix 1.0.3-SNAPSHOT:
[INFO] 
[INFO] Apache Helix ....................................... SUCCESS [  1.529 s]
[INFO] Apache Helix :: Metrics Common ..................... SUCCESS [  2.090 s]
[INFO] Apache Helix :: Metadata Store Directory Common .... SUCCESS [  1.337 s]
[INFO] Apache Helix :: ZooKeeper API ...................... SUCCESS [  2.756 s]
[INFO] Apache Helix :: Helix Common ....................... SUCCESS [  1.364 s]
[INFO] Apache Helix :: Core ............................... SUCCESS [ 13.272 s]
[INFO] Apache Helix :: Admin Webapp ....................... SUCCESS [  2.367 s]
[INFO] Apache Helix :: Restful Interface .................. SUCCESS [  4.611 s]
[INFO] Apache Helix :: Distributed Lock ................... SUCCESS [  0.921 s]
[INFO] Apache Helix :: HelixAgent ......................... SUCCESS [  1.582 s]
[INFO] Apache Helix :: Recipes ............................ SUCCESS [  0.039 s]
[INFO] Apache Helix :: Recipes :: Rabbitmq Consumer Group . SUCCESS [  0.921 s]
[INFO] Apache Helix :: Recipes :: Rsync Replicated File Store SUCCESS [  1.145 s]
[INFO] Apache Helix :: Recipes :: distributed lock manager  SUCCESS [  0.991 s]
[INFO] Apache Helix :: Recipes :: distributed task execution SUCCESS [  1.098 s]
[INFO] Apache Helix :: Recipes :: service discovery ....... SUCCESS [  1.242 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  37.906 s
[INFO] Finished at: 2022-03-08T19:54:25-08:00
[INFO] ------------------------------------------------------------------------
```

### Changes that Break Backward Compatibility (Optional)

- My PR contains changes that break backward compatibility or previous assumptions for certain methods or API. They include:

(Consider including all behavior changes for public methods or API. Also include these changes in merge description so that other developers are aware of these changes. This allows them to make relevant code changes in feature branches accounting for the new method/API behavior.)

### Documentation (Optional)

- In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Commits

- My commits all reference appropriate Apache Helix GitHub issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Code Quality

- My diff has been formatted using helix-style.xml 
(helix-style-intellij.xml if IntelliJ IDE is used)

### CODE REVIEW

**Comment by desaikomal** [comment]
code changes looks ok, but question - do we need to add any unit-tests to verify that we are passing those options appropriately to ZK?

**Comment by rabashizade** [comment]
> code changes looks ok, but question - do we need to add any unit-tests to verify that we are passing those options appropriately to ZK?

Thank you for the review. My reasoning for not adding unit tests was that there is currently no logic in Helix itself that uses these modes, and simply testing just the getMode() return values doesn't add much value. Moreover, testing the getMode() return values seems to be more of a Zookeeper test rather than a Helix test. But please let me know if these don't sound reasonable, I am open to adding tests.

**Review by narendly — APPROVED** [review]
Thanks for adding this

**Comment by rabashizade** [comment]
This PR is ready to be merged, approved by @narendly.

**Pull request merged**
