### PR TITLE
Fix unit test failure for TestTaskPerformanceMetrics.

### LINKED ISSUE #584: Fix unit test failure for TestTaskPerformanceMetrics
Each time we run unit test, the test fails.

[ERROR] Tests run: 882, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 3,710.718 s <<< FAILURE! - in TestSuite
[ERROR] testTaskPerformanceMetrics(org.apache.helix.monitoring.mbeans.TestTaskPerformanceMetrics) Time elapsed: 2.329 s <<< FAILURE!
java.lang.AssertionError: expected: but was:
at org.apache.helix.monitoring.mbeans.TestTaskPerformanceMetrics.testTaskPerformanceMetrics(TestTaskPerformanceMetrics.java:118)

### PR DESCRIPTION
**Pull request by pkuwm**
### Issues

- [x] My PR addresses the following Helix issues and references them in the PR description:

Fixes #584 

### Description

- [x] Here are some details about my PR, including screenshots of any UI changes:

The reason is thread sleeps too long. If all the jobs are completed, no new metrics are updated. so last verification would fail because last metric value won't change.
The PR fixes this failure by removing the hard code sleep time, verifying new metric values are updated and then moving forward.

### Tests

- [ ] The following tests are written for this issue:

(List the names of added unit/integration tests)

- [x] The following is the result of the "mvn test" command on the appropriate module:

[ERROR] Failures:
[ERROR]   TestJobQueueCleanUp.testJobQueueAutoCleanUp:110 Sets differ: expected [testJobQueueAutoCleanUp_JOB8, testJobQueueAutoCleanUp_JOB7, testJobQueueAutoCleanUp_JOB6, testJobQueueAutoCleanUp_JOB5, testJobQueueAutoCleanUp_JOB9] but got [testJobQueueAutoCleanUp_JOB4, testJobQueueAutoCleanUp_JOB8, testJobQueueAutoCleanUp_JOB7, testJobQueueAutoCleanUp_JOB6, testJobQueueAutoCleanUp_JOB5, testJobQueueAutoCleanUp_JOB9]
[INFO]
[ERROR] Tests run: 882, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  55:04 min
[INFO] Finished at: 2019-11-13T09:59:55-08:00

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.328 s - in org.apache.helix.integration.task.TestJobQueueCleanUp
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
### Commits

- [x] My commits all reference appropriate Apache Helix GitHub issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation in the following wiki page:

(Link the GitHub wiki you added)

### Code Quality

- [x] My diff has been formatted using helix-style.xml

### CODE REVIEW

**Comment by narendly** [comment]
@pkuwm Just to double check, could you do manual testing as well (by using print statements) and verify that the number are changing?

**Comment by pkuwm** [comment]
Have done that to troubleshoot the issue. The numbers are increasing.

**Comment by alirezazamani** [comment]
Cool. Thanks for fixing this @pkuwm.

**Comment by pkuwm** [comment]
After my fix in testTaskPerformanceMetrics, the single test runs well without a problem. But if I run all tests in helix-core, the test fails. It is very surprising to see that.
It took me a whole night to troubleshoot and find out the root cause: https://github.com/apache/helix/blob/0893044af5943e72bda721e53190d32c4a7d5dd1/helix-core/src/test/java/org/apache/helix/monitoring/mbeans/TestZkClientMonitor.java#L162 

The above setting code is a bug. After that test, the property should be clear. Otherwise, the ResetInterval would be set to 1 ms and make all the later histogram metrics reset (cause TestTaskPerformanceMetrics to fail!)

**Comment by pkuwm** [comment]
@narendly @alirezazamani This PR is ready for a final review.  As I pushed new commits, can you take a 2nd review? Thanks.

**Comment by pkuwm** [comment]
This PR is ready to be merged, approved by @narendly @alirezazamani 
commit:
```
TestTaskPerformanceMetrics fails because the thread sleeps too long and reset time window is set to 1 ms in another unit test.
The commit fixes this failure by removing the hard coded sleep time, verifying new metric values are updated and reseting time window in testCustomizedResetInterval.
```

**Pull request merged**
